# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
julia:
  - 1.4
  - nightly
env:
  global:
    - PYTHON=python3
addons:
  apt:
    packages:
      - python3-pip
before_install:
  - pip3 install pyscf
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
